/**
 * <AISparkle> — small marker pill indicating an output was authored by an LLM.
 *
 * STRICT USAGE RULE (Phase 2.1 T01):
 *   Only attach this pill to LLM-authored prose — weekly narrative cards,
 *   intensity explanation paragraphs, the per-session "Explain" panels
 *   that come back from runWeeklyLlms. DO NOT wrap deterministic compute
 *   in this pill: pace ranges (interpretRun), predicted finish times
 *   (predictedFinish), periodisation phase (currentPhase), training-load
 *   classifications, or anything else with a closed-form rules engine.
 *
 * Reviewers: flag any PR that adds <AISparkle> next to non-LLM output.
 * Council fix #4 — keep the boundary visible between AI-generated and
 * deterministic content so athletes understand what they can trust.
 */

import { IconSparkles } from "@tabler/icons-react";

export interface AISparkleProps {
  /** Pill label. Default "AI". Use "AI · Roast" or similar for variants. */
  label?: string;
  /** Pill size. Default "sm". */
  size?: "sm" | "md";
  /** Optional className overrides for layout. */
  className?: string;
}

export function AISparkle({ label = "AI", size = "sm", className = "" }: AISparkleProps) {
  const px = size === "md" ? "px-2.5 py-1" : "px-2 py-0.5";
  const text = size === "md" ? "text-[12px]" : "text-[11px]";
  const iconSize = size === "md" ? 13 : 11;
  return (
    <span
      title="Generated by Claude Haiku from structured metrics only."
      aria-label={`AI marker: ${label}`}
      style={{
        background: "var(--ai-marker-bg)",
        color: "var(--ai-marker-fg)",
      }}
      className={
        `inline-flex items-center gap-1 rounded-sm ${px} ` +
        `font-sans ${text} font-medium tracking-wide ` +
        className
      }
    >
      <IconSparkles size={iconSize} stroke={1.75} aria-hidden />
      {label}
    </span>
  );
}
