import type { WeeklyReportModel } from "@/lib/report/model";

export function WeeklyAnalysisCard({ model }: { model: WeeklyReportModel }) {
  const sections =
    model.llm?.weeklySections ?? {
      wentWell:
        "Sessions were logged for this week. Keep building consistent volume before drawing firm conclusions.",
      needsWork:
        model.findings.length > 0
          ? model.findings.map((f) => f.title).join(". ")
          : "No automated flags fired for this window.",
      nextWeek:
        "Repeat easy aerobic work with genuine recovery between stimulus sessions.",
    };

  const showAiBadge =
    model.llm?.weeklyNarrativeFromApi &&
    model.llm?.llmDisabledReason !== "no_api_key";

  return (
    <section className="mt-10" aria-labelledby="weekly-analysis-heading">
      <div className="mb-4 flex items-start justify-between gap-4">
        <h2
          id="weekly-analysis-heading"
          className="font-sans text-[15px] font-semibold"
        >
          This week
        </h2>
        {showAiBadge ? (
          <span
            className="shrink-0 rounded-sm bg-[rgba(46,94,78,0.08)] px-2 py-0.5 font-sans text-[11px] font-medium tracking-wide text-[var(--text-muted)]"
            title="Generated by Claude Haiku from structured metrics only."
          >
            ✦ AI
          </span>
        ) : null}
      </div>
      <div className="grid gap-6 rounded-[20px] border border-[rgba(213,216,224,0.45)] bg-[rgba(250,251,253,0.68)] p-6 shadow-[0_20px_40px_-16px_rgba(16,19,26,0.12)] backdrop-blur-xl md:grid-cols-3 md:p-8">
        <div>
          <h3 className="font-sans text-[12px] font-semibold uppercase tracking-wide text-[var(--status-good)]">
            Went well
          </h3>
          <p className="mt-2 text-[14px] leading-relaxed text-[var(--text-secondary)]">
            {sections.wentWell}
          </p>
        </div>
        <div>
          <h3 className="font-sans text-[12px] font-semibold uppercase tracking-wide text-[var(--status-warn)]">
            Needs work
          </h3>
          <p className="mt-2 text-[14px] leading-relaxed text-[var(--text-secondary)]">
            {sections.needsWork}
          </p>
        </div>
        <div className="md:col-span-1">
          <h3 className="font-sans text-[12px] font-semibold uppercase tracking-wide text-[var(--accent)]">
            Next week
          </h3>
          <p className="mt-2 text-[14px] leading-relaxed text-[var(--text-secondary)]">
            {sections.nextWeek}
          </p>
        </div>
      </div>
      {model.llm?.llmDisabledReason === "no_api_key" ? (
        <p className="mt-2 font-sans text-[11px] text-[var(--text-muted)]">
          LLM summaries are off until{" "}
          <code className="rounded bg-[var(--surface-raised)] px-1 font-mono text-[10px]">
            ANTHROPIC_API_KEY
          </code>{" "}
          is set on the server. Copy below uses rules + static templates.
        </p>
      ) : null}
    </section>
  );
}
